apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yelplabel-mainapp
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        app: yelplabel
    spec:
     containers:
      - name: mainapp
        image: kn45678/mainapp_project
        imagePullPolicy: Always
        

    
