# coding: utf-8

# flake8: noqa
"""
    cpuinfo

    A simple service to get cpuinfo as an example of using swagger-2.0 specification and codegen  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.cpu import CPU
